# Generated by Django 2.2.7 on 2019-11-19 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='prop',
            new_name='user',
        ),
    ]
