# Generated by Django 2.2.7 on 2019-11-19 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191119_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('Client', 'Client'), ('Company', 'Company')], help_text='Please specify if you register as Client or Company', max_length=7),
        ),
    ]
